# parameters
nc: 80  # number of classes
depth_multiple: 0.67  # model depth multiple
width_multiple: 0.75  # layer channel multiple

# anchors
anchors: 4 # auto-anchor 4 anchors per P output layer

# ESNet
backbone:
  # [from, number, module, args]
  [ [ -1, 1, CBH, [ 48, 3, 2 ] ],    # 0-P2/4
    [ -1, 1, ES_Bottleneck, [ 96, 2 ] ], # 1-P3/8
    [ -1, 3, ES_Bottleneck, [ 96, 1 ] ], # 2
    [ -1, 1, ES_Bottleneck, [ 192, 2 ] ], # 3-P5/16
    [ -1, 7, ES_Bottleneck, [ 192, 1 ] ], # 4
    [ -1, 1, ES_Bottleneck, [ 384, 2 ] ], # 5-P7/32
    [ -1, 3, ES_Bottleneck, [ 384, 1 ] ], # 6
  ]

#  CSP-PAN
head:
  [ [ -1, 1, Conv, [ 192, 1, 1 ] ], # 7
    [ [ -1, 6 ], 1, Concat, [ 1 ] ],  # cat backbone P4
    [ -1, 1, BottleneckCSP, [ 192, False ] ],  # 9 (P3/8-small)

    [ -1, 1, Conv, [ 192, 1, 1 ] ], # 10
    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 4 ], 1, Concat, [ 1 ] ],  # cat backbone P4
    [ -1, 1, BottleneckCSP, [ 192, False ] ],  # 13

    [ -1, 1, Conv, [ 192, 1, 1 ] ], # 14
    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 2 ], 1, Concat, [ 1 ] ],  # cat backbone P3
    [ -1, 1, BottleneckCSP, [ 192, False ] ],  # 17 (P3/8-small)

    [-1, 1, DWConvblock, [ 192, 5, 2 ]], # 18
    [ [ -1, 14 ], 1, Concat, [ 1 ] ],  # cat head P4
    [ -1, 1, BottleneckCSP, [ 192, False ] ],  # 20 (P4/16-medium)

    [ -1, 1, DWConvblock, [ 192, 5, 2 ] ],
    [ [ -1, 10 ], 1, Concat, [ 1 ] ],  # cat head P5
    [ -1, 1, BottleneckCSP, [ 192, False ] ],  # 23 (P5/32-large)

    [ [ -1, 7 ], 1, Concat, [ 1 ] ],  # cat head P6
    [ -1, 1, DWConvblock, [ 192, 5, 2 ] ],  # 26 (P5/32-large)

    [ [ 17, 20, 23, 25 ], 1, Detect, [ nc, anchors ] ],  # Detect(P3, P4, P5, P6)
  ]
